zeromq/zyre

- src/zyre_node.c
Solution: propagate verbose setting through to zbeacon actor.
> Problem: we lack verbose tracing of beacon activity

- src/zyre_node.c
Solution: Extend zyre_dump to include header values
> Problem: Unable to debug node header values easily.

- bindings/python/test.py
- bindings/python/zyre.py
- project.xml
A couple of bugfixes in zproject to let zyre api bindings work correctly. see `bindings/python/test.py` for a working example.
> Make zyre python bindings usable for real applications

- README.md
- api/zyre_event.xml
- bindings/python/zyre.py
- include/zyre_event.h
- project.xml
- src/zyre.c
- src/zyre_event.c
- src/zyre_node.c
Solution: Add a STOP event send from the local node in response to zyre_stop.
Motivation: A common pattern when using Zyre is to have a background
thread process zyre events, and for the main thread to control program
execution. If we want to terminate the program, we must create a
separate channel to communicate the stop signal to the background
thread, which means we cannot use a simple while loop around zyre_recv
or zyre_event_new, complicating processing unnecessarily. Now we simply
listen for the stop event over the same channel, and terminate event
processing gracefully.
> Problem: Dificult to determine when to stop processing events

- api/zyre.xml
- bindings/python/zyre.py
- bindings/qml/src/QmlZyre.cpp
- bindings/qml/src/QmlZyre.h
- bindings/qml/src/QmlZyreEvent.cpp
- bindings/qml/src/QmlZyreEvent.h
- bindings/ruby/lib/zyre/ffi.rb
- bindings/ruby/lib/zyre/ffi/event.rb
- bindings/ruby/lib/zyre/ffi/zyre.rb
- include/zyre.h
- include/zyre_event.h
- src/zyre.c
- src/zyre_event.c
- src/zyre_node.c
Solution: Rename, use macro to maintain compatibility, and implement zyre_event_print
> Problem: Print method required by CLASS api, missing print method on zyre_event

- CMakeLists.txt
- api/zyre.xml
- bindings/python/zyre.py
- bindings/qml/src/QmlZyre.cpp
- bindings/qml/src/QmlZyre.h
- bindings/qml/src/QmlZyreEvent.cpp
- bindings/qml/src/QmlZyreEvent.h
- bindings/ruby/lib/zyre/ffi/event.rb
- bindings/ruby/lib/zyre/ffi/zyre.rb
- configure.ac
- include/zyre.h
- include/zyre_event.h
- include/zyre_library.h
- src/zyre_classes.h
Solution: Remove hand-written return value 'freshness' information, and
regenerate using zproject, fixing bindings and improving documentation.
> Problem: Out of sync with current zproject capabilities

- src/zyre_event.c
Solution: return NULL for empty hash
> Problem: zyre client aborts when no headers are set

- src/zyre_event.c
Solution: the stacktrace contains issues with zmsg_is, so simply test if
self->msg is null or not
> Problem: zyre testing code segfaults at zyre_event_print

- src/zyre_event.c
Reverts zeromq/zyre#340
This PR breaks compilation. Catching a null pointer is a good idea but looking at the czmq code this is done by the zmsg_print function thus there's no need to do it here.
> Revert "Problem: zyre testing code segfaults at zyre_event_print"

- bindings/jni/src/main/c/zyre.c
- bindings/jni/src/test/java/org/zeromq/zyre/ZyreEventTest.java
ReleaseStringUTFChars was being called before the actual work was being done
> Fix broken zyre-jni selftest on linux environments

- project.xml
Specifically, this asks the user of a project to re-document the
API of that project. If Zyre uses CZMQ then it by definition uses
all CZMQ classes that are exported via its API.
Solution: fix in zproject and remove here.
> Problem: hand-specifying used classes is fragile

- api/zyre.xml
- bindings/jni/src/main/c/org_zeromq_zyre_Zyre.c
- bindings/jni/src/main/c/org_zeromq_zyre_ZyreEvent.c
- bindings/jni/src/main/java/org/zeromq/zyre/Zyre.java
- bindings/python/zyre.py
- bindings/qml/src/QmlZyre.cpp
- bindings/qml/src/QmlZyre.h
- bindings/qt/src/qzyre.cpp
- bindings/ruby/lib/zyre/ffi.rb
- bindings/ruby/lib/zyre/ffi/zyre.rb
- include/zyre.h
Solution: add this to api/zyre.xml; since zproject/5f2bad, print,
new, and destroy are not added automatically to the class.
> Problem: print method prototype was not generated

- bindings/jni/src/main/c/org_zeromq_zyre_Zyre.c
- bindings/jni/src/main/c/org_zeromq_zyre_ZyreEvent.c
Solution: disable CZMQ's signal handling.
Note: this solution may not be valid; it still needs testing. The
usual technique in CZMQ apps is to trap SIGINT and then provide a
global (zsys_interrupted) that applications can check. Further, to
interrupt any blocking calls (recv) and return null.
I think we need to expose these two features to language bindings
via a new class in CZMQ.
> Problem: Zyre traps and hides Ctrl-C

- api/zyre_event.xml
- include/zyre_event.h
- src/zyre_event.c
As zproject no longer defines this by default in all classes.
Solution: define it explicitly.
Fixes #375
> Problem: zyre_event_print was dropped from API

- builds/android/build.sh
- configure.ac
Solution: use parallel make (-j 4) and don't build man pages.
Via zproject.
> Problem: Android build is too slow

- bindings/jni/android/build.sh
Solution: pick this up from the NDK and add to jar
Fixed via zproject
> Problem: JNI Android jar missing gnustl_shared

- ci_build.sh
Solution: do not run make check for dependencies in ci_build.sh, as
they are already ran in their own CI and waste time. Already fixed in
Zproject.
> Problem: Travis CI runs tests for dependencies

- bindings/python/zyre/_zyre_ctypes.py
- bindings/ruby/lib/zyre/ffi.rb
- builds/android/ci_build.sh
- ci_build.sh
- doc/mkman
- include/zyre.h
Solution: use latest zproject which fixes this issue.
This commit includes other minimal enhancements from zproject has well.
> Problem: zyre travis build fails due to corrupt git cmd

- bindings/nodejs/README.md
- bindings/nodejs/tests/index.html
- bindings/nodejs/tests/main.js
Solution: remove passing of zyre node name via IPC, it's confusing
as we actually pass it via a global variable.
> Problem: Electron test code could be simpler

- bindings/nodejs/binding.gyp
Solution: use PRODUCT_DIR variable, at start before gyp starts
wandering all over the place (PRODUCT_DIR varies depending where
you use it.)
> Problem: nodejs: gyp can't find include files properly

- bindings/nodejs/binding.cc
Solution: send the actual message instead of the group name
> problem: shout sends group-name as message

- src/zre_msg.c
Solution: fixed in zproto and regenerated here.
> Problem: integer truncation warnings on Windows

- bindings/nodejs/binding.gyp
Solution: specify all _STATIC macros explicitly.
> Problem: NodeJS binding uses wrong (default) linkage

- bindings/nodejs/binding.cc
- bindings/nodejs/binding.h
I managed to lose a bunch of work by editing binding.cc and
binding.h until they worked, and then blindly building the
project again. Lesson: don't modify generated code. What I
wanted to do was get things working by hand, then fix the code
generator until it produced the same results. What I ended
up doing was losing some hours of work.
Lesson: when hacking generated code, copy it first.
Solution: fixed code generator and rebuilt here. The binding.cc
now exports its API via binding.h so that Zyre can call CZMQ.
> Problem: nodejs binding does not compile

- CMakeLists.txt
- Makefile.am
- configure.ac
This makes a lot of trouble for e.g. building on OpenWRT and
Android.
I'll remove the various workarounds for libuuid in zproject;
for now I've removed the dependency from CZMQ->libuuid so that
Zyre & co. don't pull it in.
> Problem: libuuid dependency sucks

- .gitattributes
- packaging/debian/changelog
- packaging/debian/copyright
- packaging/debian/libzyre1.install
Solution: Regenerated Zyre using zproject/tstgenbld.sh
For details, see https://github.com/zeromq/zproject/pull/587
> Problem: ZYRE not using latest ZPROJECT gsls

- .gitignore
- Vagrantfile
[vagrant](https://www.vagrantup.com/docs/why-vagrant/) takes the ubuntu instructions in the readme and enables developers to spin up a virtualbox instance (similar to dockerfile) with all the deps installed:
```
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: A newer version of the box 'ubuntu/trusty64' is available! You currently
==> default: have version '20160602.0.0'. The latest is version '20160708.1.0'. Run
==> default: `vagrant box update` to update.
==> default: Setting the name of the VM: zyre_default_1468408915027_50
==> default: Clearing any previously set forwarded …
```
> problem: zproject doesn't generate Vagrantfile

- src/zyre_node.c
Solution: Set the node public endpoint to be the local hostname if using any interface.
Note for this to work on windows, it also requires an earlier patch to CZMQ to ensure the hostname returned from zbeacon works with bind.
#249
> Problem: Unable to use interface "*"

- src/ztester_beacon.c
Solution: Fix the memory leak and use zstr_free instead of default
free to free strings.
fixes #484
> Problem: ztester_beacon segfaults always

- src/zyre_node.c
Solution: Check whether we're in ipv6 mode when using ipv6 notation.
> Problem: Using ipv6 zone notation in ipv4 mode

- src/zyre.c
Solution: given the private classes symbols are intentionally not
exported, the self test functions cannot be called from the external
zyre_selftest binary.
Call them instead from the main class selftest function.
> Problem: private classes self tests no longer ran

- AUTHORS
- src/zpinger.c
- src/zyre_node.c
Solutions: see commits 
Note that I'm doing final tests of zbeacon + ipv6, hope to be able to send that to CZMQ soon
> Problems: can't use zpinger with IPv6, zsys_interface/ipv6_address might not be set

- bindings/python/ci_build.sh
- bindings/python/test.py
- bindings/python/zyre/_zyre_ctypes.py
Problem: python bindings do not work with Python3
Solution: This fixes running the tests for the Python bindings with Python 3, and asks Travis to also run the test script with `python3`. See commits below.
> Fix python bindings for Python 3

- src/zyre_group.c
- src/zyre_node.c
- src/zyre_peer.c
- src/zyre_peer.h
Solution: print a debug message but do not crash and clean up the
peer instead if a connection is impossible
> Problem: crash when connecting to IPv4 peer with IPv6 enabled

- src/zyre.c
Solution: Remove the private test calls within zyre_test as zproject
now takes care of private tests as well.
> Problem: private selftests are run twice

- src/zyre_node.c
- src/zyre_peer.c
Solutions: see commits
```
src/zyre_node.c:695:9: error: logical not is only applied to the left hand side of this comparison [-Werror,-Wlogical-not-parentheses]
if (!rc == 0)
^   ~~
src/zyre_node.c:695:9: note: add parentheses after the '!' to evaluate the comparison first
if (!rc == 0)
^
(      )
src/zyre_node.c:695:9: note: add parentheses around left hand side expression to silence this warning
if (!rc == 0)
^
(  )
1 error generated.
```
> Problems: a few build problems

- .travis.yml
Solution: install python3 with brew as it's not installed by default
> Problem: OSX python3 bindings test fails

- src/zyre_node.c
As discussed in #523, the RFC for ZRE allows sending empty headers. This patch fixes an assertion currently raised when that occurs.
> Problem: ENTER events crash without headers.

- README.md
Solution: Generate from latest gitdown which uses markdown anchors
instead.
> Problem: manual markdown anchors cause conflict in github

- src/zyre_node.c
Solution: Attached commits ensure that peers are only kept alive on messages over the DEALER/ROUTER pair and not the beacons.
> Problem: Peers are incorrectly kept alive by UDP beacons after TCP connection has dropped.

- project.xml
solution: add license property to project.xml (mirroring czmq/project.xml)
```
...
gsl/4 M: Building Mingw32 build system (mingw32)
gsl/4 M: Building Packaging for NuGet (nuget)
gsl/4 M: Building service for Open Build Service (obs)
gsl/4 M: Building Python binding (python)
gsl/4 M: Building Python CFFI binding (python_cffi)
(zproject_python_cffi.gsl 346) Undefined expression: project.license
```
surprised only python CFFI cares(?) and that it wasn't in there ?
> Problem: project.xml missing license prop, python cffi bindings complain

- bindings/python_cffi/zyre/build_zyre_cffi.py
- bindings/python_cffi/zyre_cffi.py
- bindings/python_cffi/zyre_cffi/dlopen.py
https://github.com/zeromq/zproject/pull/964 (merged)  Contains the ultimate fix
__Problem:__ If we are going to call `find_library()`on line 25 then we must define it first or a NameError could be raised at runtime.
__Solution:__ `from ctypes.util import find_library` https://docs.python.org/3/library/ctypes.html#finding-shared-libraries
> from ctypes.util import find_library

- .travis.yml
- api/zyre.api
- bindings/jni/src/main/c/org_zeromq_zyre_Zyre.c
- bindings/jni/src/main/java/org/zeromq/zyre/Zyre.java
- bindings/lua_ffi/zyre_ffi.lua
- bindings/nodejs/README.md
- bindings/nodejs/binding.cc
- bindings/nodejs/binding.h
- bindings/python/zyre/_zyre_ctypes.py
- bindings/python_cffi/zyre_cffi/Zyre.py
- bindings/python_cffi/zyre_cffi/_cdefs.inc
- bindings/python_cffi/zyre_cffi/cdefs.py
- bindings/qml/src/QmlZyre.cpp
- bindings/qml/src/QmlZyre.h
- bindings/qt/src/qzyre.cpp
- bindings/ruby/lib/zyre/ffi.rb
- bindings/ruby/lib/zyre/ffi/zyre.rb
- include/zyre.h
- src/zyre.c
- src/zyre_classes.h
- src/zyre_node.c
- src/zyre_peer.c
[note- the linux boxes built / tested ok on travis, but the OSX boxes are queued, feel free to wait until those clear out to merge]
https://travis-ci.org/wesyoung/zyre/builds/275558707
solution: catch and un-wrap HELLO messages to check for public key header when new connection happens (missed in the original PR)
+ updated .travis.yml to NOT use sudo for valgrind testing (see mailing list for more info)
+ cleaned up un-necessariy set_beacon_version function left over in gsl xml
+ regen zproject headers to last working zproject state (recent PR throws errors, zproject travis check will fail until that's cleaned up)
+ cleaned up zyre-curve tests and debugging info (to use `if (verbose)` more
+ added improved ZMQ2|3 detection where ZMQ_CURVE is not defined
> [WIP] problem: HELLO messages do no contain X-PUBLICKEY header, other debug/test fixes

- src/zyre_node.c
This fully reverts the change that attempted to set the log prefix to
the actor args (which in zyres case is a zsock pipe).
> problem: log prefix is NULL

- api/zyre.api
- include/zyre.h
- src/zyre.c
- src/zyre_node.c
This enables an external discovery actor to introduce zyre nodes.
> problem: can't require peer from outside the actor

- src/zyre_node.c
solution: check that ->publickey is not null before ... trying to decode ... null. :)
(causes a segfault in non-curve mode)
> problem: missing public key check in non-curve mode

- src/zyre_node.c
solution: fix where we process gossip publishes, insert fix for setting CURVE on self->inbox during SET ENDPOINT (curve has to happen prior to the bind)
> problem: not handling endpoint/public keys correctly during gossip publishes, set endpoint not binding curve properly to socket

- src/zyre_node.c
- src/zyre_peer.c
- src/zyre_peer.h
When dumping zyre state, include all information from peers including
uuid,name,endpoint,status,and sequence numbers.
This changes the peer lines from
- 2C4C71325429324D62067181111DD4BA
- 6C22F14923E148F41662EDED5B10A27F
to
- uuid=2C4C71325429324D62067181111DD4BA name= endpoint=tcp://192.168.2.20:49152 connected=yes ready=no sent_seq=21 want_seq=0
- uuid=6C22F14923E148F41662EDED5B10A27F name=vm1 endpoint=tcp://192.168.2.187:13000 connected=yes ready=yes sent_seq=326 want_seq=204
> problem: zyre dump doesn't include peer information

- README.md
- api/zyre.api
- bindings/jni/src/main/java/org/zeromq/zyre/Zyre.java
- bindings/lua_ffi/zyre_ffi.lua
- bindings/nodejs/README.md
- bindings/python/zyre/_zyre_ctypes.py
- bindings/python_cffi/zyre_cffi/Zyre.py
- bindings/python_cffi/zyre_cffi/_cdefs.inc
- bindings/python_cffi/zyre_cffi/cdefs.py
- bindings/qml/src/QmlZyre.cpp
- bindings/qml/src/QmlZyre.h
- bindings/qt/src/qzyre.cpp
- bindings/ruby/lib/zyre/ffi/zyre.rb
- doc/zyre.doc
- doc/zyre.txt
- include/zyre.h
- src/zyre.c
- src/zyre_node.c
Solution: return empty string for endpoint if peer does not exist
> Problem: assertion fails when requesting endpoint of non-existent peer

- api/python_cffi.slurp
- api/zyre.api
- bindings/jni/src/main/c/org_zeromq_zyre_Zyre.c
- bindings/jni/src/main/java/org/zeromq/zyre/Zyre.java
- bindings/lua_ffi/zyre_ffi.lua
- bindings/nodejs/README.md
- bindings/nodejs/binding.cc
- bindings/nodejs/binding.h
- bindings/python/zyre/_zyre_ctypes.py
- bindings/python_cffi/zyre_cffi/Zyre.py
- bindings/python_cffi/zyre_cffi/cdefs.py
- bindings/qml/src/QmlZyre.cpp
- bindings/qml/src/QmlZyre.h
- bindings/qt/src/qzyre.cpp
- bindings/ruby/lib/zyre/ffi.rb
- bindings/ruby/lib/zyre/ffi/zyre.rb
- include/zyre.h
- src/zyre.c
- src/zyre_classes.h
- src/zyre_node.c
solution: add DRAFT functionality to bind to a local endpoint, while providing an advertised public ip as the endpoint gossip should publish through the mesh (rather than the default private address).
decided to try a more explicit route here instead of trying to do address rewrites (yet), because in certain situations a node may connect out one gateway (eg: it's own NAT) but home on a different public IP (and port it can control). this happens a lot on things like AWS where you may have a node that's not publicly accessible via it's default adapter, which accesses the internet through a NAT gateway- but listens for zyre traffic on a different adapter using a public IP and set of firewall rules that differ from it's management interface.
it's kind of an odd ball case- but also why i want …
> problem: zyre doesn't support a way to provide an alternative (public) endpoint (eg: in NAT situations)

- bindings/python/ci_build.sh
Solution: change to directory where libczmq.dlyb is, as
LD_LIBRARY_PATH/DYLD_LIBRARY_PATH do not work anymore on OSX
> Problem: Python bindings test fails on OSX

- src/zyre_node.c
#575, free memory if zyre_node_recv_beacon( ) returns half way.
> #575, free memory if zyre_node_recv_beacon( ) returns half way

- src/zyre.c
This fixes #583 
I went through all functions in `zyre.c` and added asserts for all pointers of the arguments except for va_lists...
> Problem: Some API Inputs are checked before accessed

- src/zyre.c
Solution: don't assert if the name is NULL, it's allowed and checked
later anyway
Fixes https://github.com/zeromq/zyre/issues/588
> Problem: zyre_new API change breaks backward compat

- README.md
Solution: Update README.md, accordingly (issue #595).
> Problem: #594 missed README.md, when renamed zyre_set_ephemeral_port().

- include/zyre_library.h
- src/zpinger.c
- src/zyre_classes.h
- src/zyre_group.c
- src/zyre_group.h
- src/zyre_node.c
- src/zyre_peer.c
- src/zyre_peer.h
Solution: don't send empty public key in beacon in legacy mode. Also simplify internal code by removing unneeded ifdefs and add curve mode to zpinger.
> Problem: draft beacon not compatible with non draft

- bindings/python_cffi/zyre_cffi/cdefs.py
- src/zyre_node.c
- src/zyre_peer.c
Solution: use only stable APIs, and while here regenerate out-of-date bindings
> Problem: build with non-DRAFT CZMQ broken

- project.xml
Solution: declare that we do not care that project and class header names can collide
Signed-off-by: Jim Klimov <EvgenyKlimov@eaton.com>
Note: Matches https://github.com/zeromq/zproject/pull/1109
> Problem: zproject requires that class name differs from project name

- src/zyre_node.c
Solution: given it's not necessary as no variables are written, remove
it.
> Problem: build broken with Werror due to braced group

- api/python_cffi.slurp
- api/zyre.api
- bindings/jni/src/main/c/org_zeromq_zyre_Zyre.c
- bindings/jni/src/main/java/org/zeromq/zyre/Zyre.java
- bindings/lua_ffi/zyre_ffi.lua
- bindings/nodejs/README.md
- bindings/nodejs/binding.cc
- bindings/nodejs/binding.h
- bindings/python/zyre/_zyre_ctypes.py
- bindings/python_cffi/zyre_cffi/Zyre.py
- bindings/python_cffi/zyre_cffi/cdefs.py
- bindings/qml/src/QmlZyre.cpp
- bindings/qml/src/QmlZyre.h
- bindings/qt/src/qzyre.cpp
- bindings/ruby/lib/zyre/ffi.rb
- bindings/ruby/lib/zyre/ffi/zyre.rb
- include/zyre.h
- src/.gitignore
- src/zyre.c
- src/zyre_classes.h
- src/zyre_node.c
solution: add it since ZYRE already takes care of node staleness (pings/pongs/evasive/EXIT)
in your application code when you see an EXIT (and you're using gossip) you just trigger an UNPUBLISH of the node (uuid) to remove the node from your local gossip cache IF you want to. that way when new nodes join, you're not re-broadcasting dead nodes to new connections.
a high level example of this in `wesyoung/pyzyre` is forthcoming for testing. hopefully one day this will be more baked into zgossip itself, wanted to start at the higher level and test (over the wide open internet) then push some of those ideas down into czmq as they mature.
reference (and merge PRE-REQ): https://github.com/zeromq/czmq/pull/1943
> problem: zyre missing GOSSIP UNPUBLISH command

- src/zyre_node.c
zyre_set_endpoint supports ephemeral ports. If didn't set an endpoint explicitly, it required every peer can access each other by hostname,that was a limit.
in zyre_node.c , 
`self->endpoint = endpoint;` 
to 
`
zstr_free(&endpoint);
self->endpoint = strdup(zsock_endpoint(self->inbox)); 
`
> zyre_set_endpoint supports ephemeral ports

- src/zyre_event.c
While the code as it is works fine on my Linux virtual machine, it fails on my MacOS laptop using nix.
Without a call to `zyre_set_endpoint`, upon joining, the gossip endpoint somehow resolves to `tcp://(null):49152` which fails to connect. Calling zyre_set_endpoint fixes it.
> zyre_event selftest needs zyre_set_endpoint on some systems

- src/CMakeLists-local.txt
If `zyre` is built with:
> cmake .. -DZYRE_BUILD_SHARED=OFF -DZYRE_BUILD_STATIC=ON
there will be a link error when building `example/chat` as it tried to link against `zyre`.
> Problem: link error when only static lib is built

- api/zyre.api
- examples/chat/chat.c
- include/zyre.h
- src/zyre.c
- src/zyre_node.c
Solution : introduce a new SILENT event triggered one second after EVASIVE currently is if ping has not been answered.
NB: the EVASIVE event could safely be deprecated with this modification and that would avoid triggering an event that does not make sense if peer is just quiet for some time (which makes sense in many cases).
> Problem : the evasive event is not meaningful enough to detect possibly dead peers

- .travis.yml
OS X builds of the python bindings fail because the `python@2` homebrew package is already installed.
Before: https://travis-ci.org/zeromq/zyre/jobs/618737916
After: https://travis-ci.org/elijahr/zyre/jobs/627524241
> Fix Travis CI OSX Build of Python bindings

- src/zyre.c
Track return codes from zstr_sendm() and zmsg_send() in order to propagate errors through zyre_shout()
Exploratory pull request.
I was interested in tracking error codes when using zyre_shout(), however zyre_shout() always returns 0.
This is also the design behind other API calls like zyre_whisper().
> Track return codes

- src/zyre_node.c
Solution: Include the reason why the beacon was tossed. Meaning which
version was expected but which version was encountered.
> Problem: Tossing beacon debug msg is unspecific

- include/zyre.h
- src/zyre.c
Hello,
I found when mixing libraries which are built upon czmq (like zyre) vs the raw libzmq library you can run into compatibility issues with polling and similar functions that need to look at the sockets for new data.
Zyre already exposes the czmq socket via zyre_socket so I propose another function zyre_socket_zmq that will expose the underlying zmq socket.
Adding this functionality allows easy mixing of the zyre library with some of the other C++ based libraries in the repo (most built on libzmq).
> Allow access to underlying raw ZMQ socket for cross library compatibility

- api/zyre.api
- include/zyre.h
Added a note in the comments that the interface when calling zyre_set_interface may now be specified with an adapter name OR an associated IP address. This behavior was added to czmq in this PR https://github.com/zeromq/czmq/pull/2062
I am unsure where else the documentation needs to be updated to explain this
> Documentation Update

- .travis.yml
- bindings/python_cffi/zyre_cffi/cdefs.py
- ci_deploy_obs.sh
- packaging/obs/_service
Solution: now that tar_scm supports @PARENT_TAG@ as a revision to
automatically fetch the most recent tag on the default branch, use
it to simplify everything
https://github.com/openSUSE/obs-service-tar_scm/pull/359
> Problem: release script for OBS build fails often

- api/zyre_event.api
- include/zyre_event.h
- src/zre_msg.c
- src/zyre_node.c
This is a bug in automatic code generation which places all headers in include by default
> Keep zre_msg.h in src directory

- packaging/redhat/zyre.spec
- project.xml
Solution: use MPL-2.0 instead of MPLv2
> Problem: linters want SPDX license shortnames

- src/zyre_election.c
- src/zyre_node.c
Solution: Start a new election - or reset the current one if it's still in progress - when a peer leaves
Not resetting the election when a peer leaves during a running election triggered a loop between zyre nodes resulting in endless JOIN/LEAVE messages being sent.  
Now, the election AND the group leader (if any) is reset whenever a peer joins or leaves an election channel.  
I also renamed some variables while trying to understand the election process and kept those names because I feel it eases the understanding of the code.
> Problem: Election do not reset when a peer leaves while the election is in progress

- project.xml
Failure detected with 'xmlstarlet' and 'xpath':
```
prompt> xmlstarlet val -w ./project.xml
./project.xml - invalid
prompt> xpath ./project.xml '/project/text()'
duplicate attribute at line 8, column 4, byte 242:
email = "zeromq-dev@lists.zeromq.org"
url = "https://github.com/zeromq/zyre"
license = "MPL-2.0"
===^
repository = "https://github.com/zeromq/zyre"
unique_class_name = "0"
at /usr/lib64/perl5/vendor_perl/XML/Parser.pm line 187.
prompt>
```
Confirmation:
```
<project
name = "zyre"
description = "an open-source framework for proximity-based P2P apps"
script = "zproject.gsl"
license = "MPL-2.0"                       <---
email = "zeromq-dev@lists.zeromq.org"
url = "https://github.com/zeromq/zyre"
license = "MPL-2.0"                       <--- Duplicate entry.
repository = …
```
> Problem: Invalid project.xml XML file.

- README.md
- README.txt
See also https://github.com/zeromq/libzmq/pull/4427 for reference.
`git clone git://gihub.com` no more supported:
```
prompt> cd zyre
prompt> find . -type f | grep -v '/.git/' | xargs grep 'git://github.com'
./README.md:    git clone git://github.com/zeromq/libzmq.git
./README.md:    git clone git://github.com/zeromq/czmq.git
./README.md:    git clone git://github.com/zeromq/zyre.git
./README.md:    git clone git://github.com/zeromq/libzmq.git
./README.md:    git clone git://github.com/zeromq/czmq.git
./README.md:    git clone git://github.com/zeromq/zyre.git
./README.md:git clone git://github.com/zeromq/libzmq.git
./README.md:git clone git://github.com/zeromq/czmq.git
./README.md:git clone git://github.com/zeromq/zyre.git
./README.txt:    git clone git://github.com/zeromq/libzmq.git …
```
> Problem: Documentation shows invalid links.

- bindings/jni/build.gradle
Solution: Remove JCENTER() call, from Android repository search path.
See
- ZPROJECT [issue 1314](https://github.com/zeromq/zproject/pull/1314) for more details.
- ZPROJECT [issue 1315](https://github.com/zeromq/zproject/pull/1315) for more questions.
> Problem: JCENTER/BINTRAY no more available for Android repositories

- bindings/delphi/libzyre.pas
Solution: Regenerate Delphi bindings.
> Problem: Delphi bindings out of sync with ZProject (mostly about comments).

- src/zyre_node.c
The boolean expression checking if the elections must be re-evaluated upon a peer exit let a new election start even if it is not necessary.  
Elections must be restarted upon a peer exit when  
- there was an election running, so the current election is canceled and a new one starts
- there was no election running but the current leader left  
Previous code restarted elections on any peer exit when there was no election running.
Solution: Fix the boolean expression to re-start elections only on leader exit when there are no elections running.
> Problem: Elections are restarted even if a non-leader (follower) peer left

- src/zyre_node.c
Previous PR about single participant in elections did not clean the group structure properly.  
This was causing crashes in specific situations when there have been an election, then one peer was left alone in this election. The structure was not clean and thus when some other peer left, when read garbage memory.
Solution: Clean leader/election attributes of zyre_group when dealing with single participant in elections.
NOTE:
5d15a8b First commit cleans up the attributes.  
908553a Second commit change some ifs to avoid checking the same condition multiple times. 
1f163ef Bump the patch version to track bugfix
> Problem: Crash (abort/sigsegv) when dealing with single participant in elections

- src/zyre.c
- src/zyre_node.c
The current hardcoded reap interval of 1 second causes evasive/silent/expired timeouts of less than 1 second to be completely ineffective since the timeouts are checked anyway at every reap interval.
This PR changes it so that it uses the smallest of the timeouts for reap interval instead and only uses the hardcoded value as the maximum reap interval when big timeouts are being used, thus not breaking the backwards compatibility but allowing small timeouts to work as expected.
Also added a test case which tests the basic functionality of the EVASIVE timeout.
> Adjust reap interval based on timeouts
