doc/zre_msg.doc
doc/zre_msg.txt
doc/zyre.doc
doc/zyre.txt
doc/zyre_event.doc
doc/zyre_event.txt

Solution: regenerate via zproject

Problem: project files are out of date

---

bindings/python/zyre.py
bindings/qml/src/QmlZyre.cpp
bindings/qml/src/QmlZyre.h
bindings/qml/src/QmlZyreEvent.cpp
bindings/qml/src/QmlZyreEvent.h
bindings/ruby/lib/zyre/ffi.rb
bindings/ruby/lib/zyre/ffi/event.rb
bindings/ruby/lib/zyre/ffi/zyre.rb
include/zyre.h
include/zyre_event.h

Solution: update all project files

Problem: generated with old/wrong version of zproject

---

include/zre_msg.h
src/zre_msg.bnf
src/zre_msg.c

Solution: Regenerate using zproto

Problem: Out-of-date zre_msg protocol code.

---

src/perf_local.c
src/ztester_beacon.c
src/ztester_gossip.c
src/zyre_node.c
src/zyre_peer.c

Problem: #322
Solution: Replace zclock_time() with zclock_mono()

Problem: #322

---

CONTRIBUTING.md
README.md

Solution: Reuse the one from CZMQ with adjustments to Zyre

Problem: Zyre doesn't have a contribution guideline

---

bindings/jni/src/main/java/org/zeromq/zyre/Zyre.java
bindings/jni/src/main/java/org/zeromq/zyre/ZyreEvent.java

Solution: fixed in zproject, regenerate here

Problem: JNI API has extraneous 'self' argument

---

bindings/jni/src/main/c/org_zeromq_zyre_Zyre.c
bindings/jni/src/main/c/org_zeromq_zyre_ZyreEvent.c
bindings/jni/src/main/java/org/zeromq/zyre/Zyre.java
bindings/jni/src/main/java/org/zeromq/zyre/ZyreEvent.java

Solution: fixed in zproject, regenerated here
Fixes #1212 in CZMQ.

Problem: JNI API is not using proper classes

---

bindings/jni/build.gradle
bindings/jni/src/main/java/org/zeromq/zyre/Zyre.java
bindings/jni/src/main/java/org/zeromq/zyre/ZyreEvent.java

This PR partially fixes the build issues. The remaining ones appear do be in czmq

Problem: automated jni build missing build dependencies and import statements

---

api/zyre.xml
api/zyre_event.xml
bindings/jni/src/main/c/org_zeromq_zyre_ZyreEvent.c
bindings/jni/src/main/java/org/zeromq/zyre/Zyre.java
bindings/jni/src/main/java/org/zeromq/zyre/ZyreEvent.java
bindings/python/zyre.py
bindings/qml/src/QmlZyre.cpp
bindings/qml/src/QmlZyre.h
bindings/qml/src/QmlZyreEvent.cpp
bindings/qml/src/QmlZyreEvent.h
bindings/qt/src/qzyre.cpp
bindings/qt/src/qzyreevent.cpp
bindings/qt/src/qzyreevent.h
bindings/ruby/lib/zyre/ffi/event.rb
bindings/ruby/lib/zyre/ffi/zyre.rb
include/zyre.h
include/zyre_event.h

Solution: needs imports
Also, zyre_event_new was passing 'self' wrongly; it should have been
'node'.

Problem: JNI was not building successfully

---

bindings/jni/src/main/c/org_zeromq_zyre_Zyre.c
bindings/jni/src/main/c/org_zeromq_zyre_ZyreEvent.c

Solution: regenerate from zproject

Problem: JNI bindings are out of date

---

.travis.yml

Problem: Travis still trying to build qt-android

---

src/zyre_node.c

Fixes #381, Adding interface name to the address for IPv6 addresses.

Adding interface to the endpoint in case of IPv6 address

---

bindings/jni/android/CMakeLists.txt
bindings/jni/android/build.sh

Solution: fixed in zproject, regenerated here.
Fixes #390

Problem: link failure when initializing JNI lib on Android

---

CMakeLists.txt

Solution: fixed in zproject, regenerate here.

Problem: cmake fails in add_test given test NAME "zyre"

---

bindings/jni/android/build.sh
bindings/jni/msvc/platform.h
builds/android/build.sh
builds/msvc/platform.h

Solution: fixed in zproject; regenerated here.
You need only run ./build.sh in bindings/jni/android.
Fixes #395

Problem: zyre-android.jar lacks libczmqjni.so.

---

Findczmq.cmake
Findlibsodium.cmake
Findlibzmq.cmake
configure.ac
include/zyre.h

Solution: regenerate via zproject.

Problem: CMake find package support was broken

---

.travis.yml

Solution: add Valgrind and uuid-dev to the Travis dependencies

Problem: Travis CI fails due to missing Valgrind

---

.travis.yml
CMakeLists.txt
builds/cmake/ci_build.sh

Problem: more build issues

---

Makefile.am
configure.ac
examples/chat/Makefile.am

Solution: fix autotools to make it build again

Problem: chat build is broken

---

.travis.yml

Solution: request docker and latest git

Problem: check_project and check_proto are broken

---

.travis.yml

Solution: do not check_zproject and check_zproto under osx

Problem: travis osx does not support docker

---

bindings/nodejs/.gitignore
bindings/nodejs/binding.cc
bindings/nodejs/binding.gyp
bindings/nodejs/build.sh
bindings/nodejs/package.json
bindings/nodejs/test.js

Solution: start to use electron-rebuild
Note: this pulls electron-prebuilt and electron-rebuild into the local
node_modules directory.

Problem: can't build Zyre for Electron

---

bindings/nodejs/binding.cc
bindings/nodejs/binding.gyp
bindings/nodejs/build.sh
bindings/nodejs/package.json
bindings/nodejs/test.js
ci_build.sh
doc/mkman
doc/zyre.doc
doc/zyre.txt
doc/zyre_event.doc
doc/zyre_event.txt
include/zyre.h
include/zyre_event.h

Working on Node.js binding

---

bindings/nodejs/README.md
bindings/nodejs/binding.cc
bindings/nodejs/build.sh
include/zyre.h
include/zyre_event.h
src/Makemodule.am

Solution: add more methods to the binding
Also fixed a link error (libm) in static builds.

Problem: nodejs binding did not send/recv messages

---

bindings/nodejs/hellozyre/index.html
bindings/nodejs/hellozyre/main.js
bindings/nodejs/hellozyre/package.json

Solution: add hellozyre test case (this is temporary until we get this better organized)

Problem: we need a test case for Node.js in Electron

---

bindings/nodejs/binding.gyp
bindings/nodejs/build.sh

Solution: build.sh should have deps/lib/pkgconfig instead

Problem: build.sh has a wrong PKG_CONFIG_PATH value

---

src/zpinger.c

Solution: add -i/--interface option for this

Problem: can't run zpinger on specific interface

---

bindings/nodejs/binding.cc

Solution: correct typos in binding.cc where faulty indexes were used

Problem: whisper and setHeader not working correctly

---

.gitignore
README.md

Solution: Update build instructions for both Linux and Windows in README.md

Problem: Build instructions are out of date in README.md

---

Makefile.am

Solution: regenerate from zproject

Problem: Makefile.am did not package README.txt

---

bindings/nodejs/binding.cc
bindings/nodejs/binding.gyp
bindings/nodejs/binding.h

Solution: did a lot of work on NodeJS binding; regenerated here.

Problem: NodeJS binding does not work with CZMQ classes

---

src/zyre_event.c

Let Travis complete before merging as this is a fix for travis issues

use gossiping to overcome travis issues

---

.travis.yml

Solution: add a Valgrind run using zproject's build on Travis

Problem: no Valgrind test on Travis CI

---

Dockerfile
api/zyre.api
bindings/jni/README.md
bindings/jni/android/build.sh
bindings/jni/src/main/c/org_zeromq_zyre_Zyre.c
bindings/jni/src/main/java/org/zeromq/zyre/Zyre.java
bindings/nodejs/README.md
bindings/nodejs/binding.cc
bindings/nodejs/binding.h
bindings/python/zyre/_zyre_ctypes.py
bindings/python_cffi/zyre_cffi.py
bindings/qml/src/QmlZyre.cpp
bindings/qml/src/QmlZyre.h
bindings/qt/src/qzyre.cpp
bindings/ruby/lib/zyre/ffi.rb
bindings/ruby/lib/zyre/ffi/zyre.rb
builds/android/android_build_helper.sh
builds/android/build.sh
builds/android/ci_build.sh
ci_deploy.sh
include/zyre.h
project.xml
setup.py
src/zyre.c
src/zyre_group.c
src/zyre_group.h
src/zyre_node.c

Solution: Add a new API call to get all peers from one group. This requires the peer to be in that group.
+ zproject fixes

Problem: Cannot obtain a list of all peer for just one group

---

README.md
doc/zpinger.doc
doc/zpinger.txt
doc/zre_msg.doc
doc/zyre.doc
doc/zyre.txt
doc/zyre_event.doc
doc/zyre_event.txt
src/zyre_node.c

* Regenerate docs
* Simplified zyre_node's own_groups attr. to avoid confusion
* More information in zyre_node_dump()

Documenation, Own Groups improvement, Nicer Dumping

---

README.md
doc/mkman
doc/zpinger.doc
doc/zre_msg.doc
doc/zyre.doc
doc/zyre_event.doc

Problem: docs are out of sync (zproject has evolved!)

---

Vagrantfile

updated Vagrantfile as now generated by zproject: https://github.com/zeromq/zproject/blob/master/zproject_vagrant.gsl

problem: Vagrantfile out of date with zproject

---

builds/rpi/README.md
packaging/debian/rules
packaging/redhat/zyre.spec

Problem: out of date with zproject

---

include/zyre.h

Problem: out of sync with zproject

---

CMakeLists.txt
bindings/jni/README.md
bindings/jni/android/build.sh
bindings/jni/build.gradle
bindings/jni/msvc/resource.rc
bindings/qt/buildlib/buildlib.pro
bindings/ruby/lib/zyre/ffi/version.rb
builds/msvc/nuget/package.nuspec
builds/msvc/nuget/package.targets
builds/msvc/resource.rc
configure.ac
include/zyre_library.h
packaging/debian/changelog
packaging/debian/zyre.dsc.obs
packaging/redhat/zyre.spec
project.xml

Solution: Bump zyre version to 1.3.0 which is next in row.

Problem: zyre version has not been increased after release

---

src/zyre_event.c
src/zyre_group.c
src/zyre_node.c

Solution: use zhash_first/next in a for loop instead.

Problem: zhash_foreach is deprecated

---

src/zyre_node.c

Solution: Defer creation of beacon until the beacon is able to give us a valid hostname

Problem: Zyre would fail to start if the beacon cannot yet bind

---

CMakeLists.txt
Dockerfile
Vagrantfile
bindings/jni/build.gradle
bindings/qt/src/qzhash.cpp
bindings/qt/src/qzhash.h
bindings/qt/src/qzsock.cpp
bindings/qt/src/qzsock.h
builds/check_zproject/ci_build.sh
builds/cmake/ci_build.sh
builds/msvc/vs2010/libzyre/libzyre.props
builds/msvc/vs2012/libzyre/libzyre.props
builds/msvc/vs2013/libzyre/libzyre.props
builds/msvc/vs2015/libzyre/libzyre.props
builds/rpi/build.sh
builds/valgrind/ci_build.sh
ci_build.sh
ci_deploy.sh
configure.ac
doc/Makefile.am
include/zyre_library.h
src/zyre_classes.h
src/zyre_selftest.c

Problem: outofdate with zproject

---

CMakeLists.txt
configure.ac
project.xml

Solution: add it and regenerate

Problem: ABI not set in project.xml

---

README.md
README.txt

Problem: badges in README show only build status of Linux

---

.travis.yml

Problems: CI build does not use containers, python3 test fails

---

src/perf_local.c
src/perf_remote.c

Solution:
Lower default from 100 nodes (which is impossible on Windows due to socket limit
Remove 1s receive timeouts that effect results
Handle updated event format (peer name between uuid and group/content)
Prevent writes past array end (index into peers buffer not checked)

Problem: Unable to run performance tests on Windows due to socket limit

---

src/zyre_node.c
src/zyre_peer.c

Solution: see commits
Fixes #518

Problem: zyre still not fully working with IPv6 link-local

---

.travis.yml
bindings/python_cffi/zyre_cffi/cdefs.py
packaging/debian/copyright

Solutions: regen, move to 14.04, don't run brew update unless necessary

Problems: out of date with CZMQ, Travis still using 12.04, OSX builds too slow

---

src/zyre.c

solution: fixing comment paste error from previous PR

problem: copy paste error

---

src/zyre_node.c

This fixes 3 small issues with the new curve support:
* Automatically sets the X-PUBLICKEY header when SET PUBLICKEY is called
* Removes a redundant if block
* Removes log_prefix - args there is the pipe, not the node name

problem: Small fixes needed for new curve features

---

src/zyre_node.c

If no X-PUBLICKEY header is present, ignore the HELLO instead of asserting.

problem: HELLO handling assertion fails on non curve clients

---

Jenkinsfile
bindings/jni/src/main/c/org_zeromq_zyre_Zyre.c
bindings/jni/src/main/java/org/zeromq/zyre/Zyre.java
bindings/lua_ffi/zyre_ffi.lua
bindings/nodejs/README.md
bindings/nodejs/binding.cc
bindings/nodejs/binding.h
bindings/python/zyre/_zyre_ctypes.py
bindings/python_cffi/zyre_cffi/Zyre.py
bindings/python_cffi/zyre_cffi/_cdefs.inc
bindings/python_cffi/zyre_cffi/cdefs.py
bindings/qml/src/QmlZyre.cpp
bindings/qml/src/QmlZyre.h
bindings/qt/src/qzyre.cpp
bindings/ruby/lib/zyre/ffi.rb
bindings/ruby/lib/zyre/ffi/zyre.rb
configure.ac
src/Makemodule.am
src/zyre_classes.h

problem: zproject out of date

---

api/zyre.api
bindings/jni/src/main/c/org_zeromq_zyre_Zyre.c
bindings/jni/src/main/java/org/zeromq/zyre/Zyre.java
bindings/lua_ffi/zyre_ffi.lua
bindings/nodejs/README.md
bindings/nodejs/binding.cc
bindings/nodejs/binding.h
bindings/python/zyre/_zyre_ctypes.py
bindings/python_cffi/zyre_cffi/Zyre.py
bindings/python_cffi/zyre_cffi/_cdefs.inc
bindings/python_cffi/zyre_cffi/cdefs.py
bindings/qml/src/QmlZyre.cpp
bindings/qml/src/QmlZyre.h
bindings/qt/src/qzyre.cpp
bindings/ruby/lib/zyre/ffi.rb
bindings/ruby/lib/zyre/ffi/zyre.rb
include/zyre.h
include/zyre_library.h
project.xml
src/zyre.c
src/zyre_classes.h
src/zyre_node.c

solution: build set_zap_domain api and apply to sockets when using curve

problem: missing set_zap_domain support when using curve

---

src/zyre.c

There have been multiple issues
* always logging in verbose mode
* duplicate function calls
* not following style guide
* leftover debug code

Cleaned up zyre selftest

---

.gitignore

Solution: add some generated files into gitignore file.

Problem: some generated files are not in the gitignore file

---

bindings/python_cffi/zyre_cffi/cdefs.py
bindings/qt/src/qzsock.cpp
bindings/qt/src/qzsock.h

Problem: CZMQ python cdefs out of date

---

builds/check_zproject/ci_build.sh
builds/cmake/clang-format-check.sh.in

WIP : Restart Travis test after merging https://github.com/zeromq/zproject/pull/1116 (if that passes) and merge this one if it passes with contemporary public zproject state.

[WIP] Regen zproject to adapt to recent changes in 2bf00bb

---

bindings/nodejs/build.sh

WIP: Still awaits merge of https://github.com/zeromq/zproject/pull/1116 ;)

Regen again for the nodejs binding script

---

src/zpinger.c
src/zyre.c
src/zyre_node.c

solution: add them.
.. by 'next week', i meant .. err yea :(

problem: draft security features missing tags.

---

.github/stale.yml

solution: create stale.yml- we can fiddle with the values as we go.

problem: missing stale config

---

.travis.yml

Solution: do not install packages as with the Android test

Problem: android build fails because packages are installed in JNI test

---

bindings/delphi/Zyre.pas
bindings/python_cffi/zyre_cffi/cdefs.py
bindings/qt/src/qzframe.cpp
bindings/qt/src/qzframe.h
bindings/qt/src/qzsock.cpp
bindings/qt/src/qzsock.h

Problem: bindings out of date with CZMQ

---

examples/minimal/minimal.c

Solution: as my attempts following documentation have failed, I've
distilled really minimal example from `chat.c`. It sends 10 messages to
the zyre group and ends.

Problem: forgot how to use zyre

---

bindings/jni/src/main/java/org/zeromq/tools/ZmqNativeLoader.java

Solution: add them
Fixes https://github.com/zeromq/zyre/issues/633

Problem: missing files from last regen

---

CMakeLists.txt
Findczmq.cmake
Findlibzmq.cmake

Solution: Regenerate with `gsl -target:cmake project.xml`

Problem: CMake stuffs out of sync with zproject

---

bindings/jni/build.gradle
bindings/jni/src/main/java/org/zeromq/tools/ZmqNativeLoader.java
bindings/jni/src/main/java/org/zeromq/zyre/Zyre.java
bindings/jni/src/main/java/org/zeromq/zyre/ZyreEvent.java

Problem: JNI bindings are out of sync

---

README.md
README.txt
examples/jni/pom.xml
examples/jni/src/main/java/org/zyre/helloworld/HighLevelApiMain.java
examples/jni/src/main/java/org/zyre/helloworld/LowLevelApiMain.java

Solution: Add examples of the JNI binding

Problem: Zyre project has no examples of JNI usage

---

README.md
README.txt

Problem: links to binary packages in READMEs out of date

---

bindings/jni/README.md
builds/android/README.md
builds/android/android_build_helper.sh
builds/android/build.sh
builds/android/ci_build.sh

Solution: Re-generate to upgrade NDK and JNI README

Problem: czmq out of sync with zproject

---

CMakeLists.txt
builds/cmake/Modules/ClangFormat.cmake
ci_deploy.sh

Solution: regenerate from zproject

Problem: zproject is out of date

---

api/python_cffi.slurp
api/zyre.api
bindings/delphi/Zyre.pas
bindings/delphi/libzyre.pas
bindings/jni/zyre-jni/src/main/c/org_zeromq_zyre_Zyre.c
bindings/jni/zyre-jni/src/main/java/org/zeromq/zyre/Zyre.java
bindings/lua_ffi/zyre_ffi.lua
bindings/python/zyre/_zyre_ctypes.py
bindings/python_cffi/zyre_cffi/Zyre.py
bindings/python_cffi/zyre_cffi/cdefs.py
bindings/qml/src/QmlZyre.cpp
bindings/qml/src/QmlZyre.h
bindings/qt/src/qzyre.cpp
bindings/qt/src/qzyre.h
bindings/ruby/lib/zyre/ffi.rb
bindings/ruby/lib/zyre/ffi/zyre.rb
include/zyre.h
src/zyre_classes.h

Add socket_zmq to zyre.api file and minor documentation updates

---

CMakeLists.txt
bindings/jni/README.md
bindings/python_cffi/zyre_cffi/cdefs.py

Solution: Re-generate!
Fixes #663

Problem: zyre out of sync with zproject

---

AUTHORS
src/zyre_node.c
src/zyre_peer.c

[related issue-671](https://github.com/zeromq/zyre/issues/671)

Problem: Curve doesn't works on Release build on Windows 10 msvc2017

---

api/zyre_event.api
src/zre_msg.bnf
src/zre_msg.c
src/zre_msg.h
src/zre_msg.xml
src/zyre_node.c

Problem: SILENT event was not declared in the API

---

bindings/python_cffi/zyre_cffi/cdefs.py

Fix: regenerate zproject
Ref. https://github.com/zeromq/zproject/issues/1266

Problem: not aligned with zproject

---

builds/android/android_build_helper.sh

Solution: Regenrate build environment using gsl, to reflect the changes made to the android template in zproject.

Problem: zyre not in sync with zproject.

---

bindings/python/_project.py
bindings/python_cffi/setup.py
packaging/redhat/zyre.spec
project.xml

Problem: license shortname does not conform with SPDX format

---

ci_build.sh

Problem: out of date with project.xml

---

src/zyre_node.c

Solution : Revert "Merge pull request #697 from roumieu/master"
However, the problem encountered in the previous pull request is not resolved, an issue will be opened to initiate the discussion.

Problem: previous pull request #697 breaks backward compatibility

---

bindings/jni/zyre-jni/android/build.sh

Correction already available in ZProject.
See https://github.com/zeromq/zproject/pull/1301 for details.

Problem: Android - Build failure on Ubuntu 22.04

---

bindings/jni/ci_build.sh
builds/android/ci_build.sh

Problem: Sync with zproject (CI build script should allow existing dependency folders).

---

bindings/jni/ci_build.sh
builds/android/ci_build.sh

Solution: Regenerate.
I really appologize.

Regression: Previsous sync was malformed for ZYRE.

---

bindings/jni/ci_build.sh
builds/android/ci_build.sh

Problem: Sync with zproject (Android build failures when <dependency>_ROOT is specified)

---

bindings/jni/build.gradle

Problem: Sync with zproject (Restore jcenter/bintray Android repository)

---

bindings/jni/ci_build.sh
bindings/jni/zyre-jni/android/build.sh

Problem: Sync with zproject (Android CI build need a way to disable GRADLE automatic tests).

---

bindings/jni/README.md
bindings/jni/ci_build.sh
bindings/jni/zyre-jni/android/build.sh
builds/android/README.md
builds/android/android_build_helper.sh
builds/android/build.sh
builds/android/ci_build.sh

Problem: Sync with zproject (ZProject ANDROID build scripts and documentations are not up-to-date, compared to LIBZMQ).

---

bindings/jni/ci_build.sh
bindings/jni/zyre-jni/android/build.sh
builds/android/build.sh

Solution: Generate ZYRE with ZProject (Android modifications only).

Problem: ZYRE (Android) is out of sync with ZProject.
